on:
  push:
    branches:
      - main
jobs:
  job1:
    name: push to gas
    runs-on: ubuntu-latest
    env:
      CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
      CLASP_JSON: ${{ secrets.CLASP_JSON }}
    steps:
      - name: push
        run: |
          echo "$CLASPRC_JSON" ~/.clasprc.json
          echo "$CLASP_JSON" > .clasp.json
          npx @google/clasp push
