on:
  push:
    branches:
      - main
jobs:
  job1:
    name: push to gas
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: |
          cp $CLASPRC_JSON ~/.clasprc.json
          echo "{\"scriptId\":\"${SCRIPT_ID}\"}" > .clasp.json
          npx @google/clasp push
