name: Push to GAS

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:
    
jobs:
  job1:
    name: push to gas
    runs-on: ubuntu-latest
    env:
      CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
      CLASP_JSON: ${{ secrets.CLASP_JSON }}
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
      - name: push
        run: |
          echo $CLASPRC_JSON > ~/.clasprc.json
          cd prod/
          echo $CLASP_JSON > .clasp.json
          npx @google/clasp push --force
